Engine/index/routes.py
from email import message
from flask import Blueprint, flash, render_template, request, url_for, jsonify, redirect
from flask_login import current_user, login_required
from Engine.models import Message, Reviewer, User, Question
from Engine import db
from sqlalchemy import insert
import os

index = Blueprint('index', __name__, template_folder='templates/index',
                  static_folder='static/index', )


@index.get("/")
@login_required
def _index():
    """Show all available reviewers"""
    pageTitle = "Dashboard"
    image_file = url_for(
        'static', filename='profile_pictures/' + current_user.profile_picture)

    reviewers = Reviewer.query.all()

    # addBasicData()

    return render_template("index.html", user_reviewers=current_user.reviewers, admin=os.getenv("ADMIN"), reviewers=reviewers, image_file=image_file, pageTitle=pageTitle)


@index.get("/collection")
@login_required
def collection():
    """Show bought reviewers"""
    pageTitle = "Collection"
    image_file = url_for(
        'static', filename='profile_pictures/' + current_user.profile_picture)

    reviewers = current_user.reviewers
    return render_template("index.html", admin=os.getenv("ADMIN"), reviewers=reviewers, image_file=image_file, pageTitle=pageTitle)


@index.get("/buy/<int:current_reviewer_id>")
@login_required
def buy_test(current_reviewer_id):
    # buying logic
    reviewer = db.session.get(Reviewer, current_reviewer_id)

    admin = User.query.filter_by(username=os.getenv('ADMIN')).first()

    text = "{name} wants to buy a reviewer for {reviewer_name}".format(
        name=current_user.first_name if current_user.first_name is not None else current_user.username, reviewer_name=reviewer.name)

    db.session.execute(insert(Message).values(
        sender_id=current_user.id,
        recipient_id=admin.id,
        message_type='buy',
        reviewer_id=current_reviewer_id,
        body=text))

    db.session.commit()
    return jsonify(message="Buy request sent! Please contact me for a faster transaction")


@ index.get("/messages")
@ login_required
def messages():

    messages = Message.query.filter_by(recipient_id=current_user.id).limit(10)

    return jsonify([{
        'id': message.id,
        'message': message.body,
        'sender': message.sender_id,
        'type': message.message_type,
        'body': message.body,
        'reviewer_id': message.reviewer_id
    } for message in messages])


@ index.post("/allow")
@ login_required
def allow():

    reviewer = db.session.get(Reviewer,  request.form.get("reviewer_id"))

    user = db.session.get(User, request.form.get("user_id"))

    user.reviewers.append(reviewer)

    db.session.execute(insert(Message).values(
        sender_id=current_user.id,
        recipient_id=request.form.get("user_id"),
        message_type='notification',
        body=f"You can now review {reviewer.name}"))

    db.session.execute(insert(Message).values(
        sender_id=current_user.id,
        recipient_id=current_user.id,
        message_type='notification',
        body=f"You allowed {user.username} to review {reviewer.name}"))

    message = db.session.get(Message, request.form.get("message_id"))

    db.session.delete(message)

    db.session.commit()

    return jsonify(message='Transaction completed')


@ index.post("/deny")
@ login_required
def deny():

    reviewer = db.session.get(Reviewer,  request.form["reviewer_id"])

    user = db.session.get(User, request.form["user_id"])

    db.session.execute(insert(Message).values(
        sender_id=current_user.id,
        recipient_id=request.form["user_id"],
        message_type='notification',
        body=f"You request to buy {reviewer.name} had been declined"))

    db.session.execute(insert(Message).values(
        sender_id=current_user.id,
        recipient_id=current_user.id,
        message_type='notification',
        body=f"You declined {user.username} to buy {reviewer.name}"))

    message = db.session.get(Message, request.form.get("message_id"))

    db.session.delete(message)

    db.session.commit()

    return jsonify(message='Request Denied')

Engine/index/templates/index/head.html
<!DOCTYPE html>
<html>

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <title>{% block title %}{% endblock %}</title>

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <!-- <script src="https://unpkg.com/@popperjs/core@2/dist/umd/popper.js"></script> -->
    <script src="{{ url_for( 'index.static' , filename='head.js')  }}"></script>
    <!--  -->
    {% block script -%}{%- endblock script %}
    <!--  -->
    {% block component_script -%}{%- endblock component_script %}

    <link rel="stylesheet" href="{{ url_for( 'index.static' , filename='head.css') }}">
    <!--  -->
    {% block style -%}{%- endblock style %}
    <!--  -->
    {% block component_style -%}{% endblock component_style %}

    <!-- {# messages #} -->
    {% with messages=get_flashed_messages() -%}
    <ul class=flashes>
        {% if messages -%} {% for message in messages -%}
        <li class="message">{{ message }}</li>
        {%- endfor %} {%- else -%}
        <li class="message">{{ message }}</li>
        {%- endif %}
    </ul>
    {%- endwith %}

</head>

<body>
    <!--  -->{% block login -%}{%- endblock login %}
    <!--  -->{% block register -%}{%- endblock register %}
    <!--  -->{% block main -%}{%- endblock %}
</body>

Engine/index/templates/index/index.html
{% extends 'navigation.html' %}

<!-- {# styles #} -->
{% block component_style -%}
<link rel="stylesheet" href="{{ url_for('index.static', filename='reviewers.css') }}"> {% endblock component_style %}

<!-- {# scripts #} -->
{% block component_script -%}
<script src="{{ url_for('index.static', filename='reviewers.js')}}" type="module"></script>
{%- endblock component_script %}

<!-- {# reviewer section #} -->
{% block reviewers -%}
<main id="reviewers">
    <div id="message-div">
        <p class="header" id="welcome-message">Welcome back <span class="header" id="welcome-username">{{current_user.username}}!</span></p>
        <div id="options" class="icon-button">
            <svg class="icon" id="menu-horizontal" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"><path d="M12,10a2,2,0,1,0,2,2A2,2,0,0,0,12,10ZM5,10a2,2,0,1,0,2,2A2,2,0,0,0,5,10Zm14,0a2,2,0,1,0,2,2A2,2,0,0,0,19,10Z"/></svg>
        </div>
    </div>
    <div id="reviewer-list">
        {% for reviewer in reviewers -%}
        <div class="reviewer">
            <div class="reviewer-title">{{ reviewer.name }}</div>
            {% if reviewer.availability == False %}
            <!--  -->
            <div class="unavailable">
                <p>Unavailable</p>
            </div>
            <!--  -->
            {%- endif %}
            <!--  -->
            {% if pageTitle == "Dashboard" -%}
            <div class="reviewer-options">
                <!-- {% if pageTitle == "Collection" -%}
                <p class="score"><span class="reviewer-score">{{score}}</span>{{reviewer.expected_score}}</p>
                {%- endif %} -->
                <!--  -->
                {% if reviewer in user_reviewers -%}
                <!--  -->
                <div class="bought-reviewer">
                    <p>Bought</p>
                </div>
                {%- else -%}
                <div data-link="{{url_for('index.buy_test', current_reviewer_id=reviewer.id)}}" class="reviewer-button buy-button icon-button">
                    <svg class="icon shopping-cart-line" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 256 256"><rect width="256" height="256" fill="none"/><circle cx="80" cy="216" r="16"/><circle cx="184" cy="216" r="16"/><path fill="none" stroke="#c4c3cd" stroke-linecap="round" stroke-linejoin="round" stroke-width="16" d="M42.28575,72H221.71429l-26.39873,92.39554A16,16,0,0,1,179.93118,176H84.06882a16,16,0,0,1-15.38438-11.60446L32.51492,37.80223A8,8,0,0,0,24.82273,32H8"/></svg>
                    <svg class="icon" id="shopping-cart-line-filled" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 256 256"><rect width="256" height="256" fill="none"/><path d="M96,216a16,16,0,1,1-16-16A16.00016,16.00016,0,0,1,96,216Zm88-16a16,16,0,1,0,16,16A16.00016,16.00016,0,0,0,184,200ZM228.10059,67.18262A7.99866,7.99866,0,0,0,221.71387,64H48.32031L40.207,35.604A16.06984,16.06984,0,0,0,24.82227,24H8A8,8,0,0,0,8,40H24.82227l9.73046,34.05469c.02637.09863.05372.19677.084.29443l26.35547,92.24365A24.10087,24.10087,0,0,0,84.06836,184h95.86328a24.101,24.101,0,0,0,23.07617-17.40674l26.39844-92.39551A8.00023,8.00023,0,0,0,228.10059,67.18262Z"/></svg>
                </div>
                <!--  -->
                {%- endif %}
            </div>
            <!--  -->
            {%- else -%}
            <div class="reviewer-options">
                <a href="{{url_for('review.start', current_reviewer_id=reviewer.id)}}" class="reviewer-button icon-button">
                    <p>Start</p>
                </a>
            </div>
            {%- endif %}
        </div>
        {%- endfor %}
    </div>
</main>
{%- endblock reviewers %}

Engine/index/templates/index/navigation.html
{%- block scripts %}
<script src="{{ url_for( 'index.static' , filename='navigation.js')  }}" type="module"></script>
{% endblock scripts -%} {% extends "head.html" %} {%- block style %}
<link rel="stylesheet" href="{{ url_for( 'index.static' , filename='navigation.css')}}"> {% endblock style -%}

<!-- {# main #} -->
{% block main -%}
<div id="grid-container">
    <section id="top-section">
        <div id="title-container">
            <p id="title">Mind Brew</p>
            <section id="navigation-section">
                <a href="{{ url_for('index._index') }}" class="nav-child" id="buy-reviewer">
                    <svg class="icon nav-icon shopping-cart-line" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 256 256"><rect width="256" height="256" fill="none"/><circle cx="80" cy="216" r="16"/><circle cx="184" cy="216" r="16"/><path fill="none" stroke="#c4c3cd" stroke-linecap="round" stroke-linejoin="round" stroke-width="16" d="M42.28575,72H221.71429l-26.39873,92.39554A16,16,0,0,1,179.93118,176H84.06882a16,16,0,0,1-15.38438-11.60446L32.51492,37.80223A8,8,0,0,0,24.82273,32H8"/></svg>
                    <!-- <p>Library</p> -->
                </a>
                <a href="{{ url_for('index.collection') }}" class="nav-child" id="my-reviewer">
                    <svg version="1.0" class="nav-icon icon" id="book-icon" xmlns="http://www.w3.org/2000/svg" width="50.000000pt" height="50.000000pt" viewBox="0 0 50.000000 50.000000" preserveAspectRatio="xMidYMid meet">
<g transform="translate(0.000000,50.000000) scale(0.100000,-0.100000)"
fill="#c4c3cd" stroke="none">
<path d="M60 288 l0 -175 53 -7 c30 -3 73 -12 95 -20 37 -13 47 -13 84 0 22 8
65 17 95 20 l53 7 0 175 0 175 -53 -7 c-30 -3 -73 -12 -95 -20 -37 -13 -47
-13 -84 0 -22 8 -65 17 -95 20 l-53 7 0 -175z m143 130 l37 -11 0 -155 0 -154
-22 6 c-13 4 -49 12 -80 18 l-58 12 0 154 0 155 43 -7 c23 -4 59 -12 80 -18z
m217 -131 l0 -153 -57 -12 c-32 -6 -68 -14 -80 -18 l-23 -6 0 156 c0 86 3 156
8 156 4 1 30 7 57 15 101 28 95 37 95 -138z"/>
<path d="M20 241 l0 -168 68 -7 c37 -3 88 -13 115 -21 41 -12 53 -12 95 0 26
8 77 18 115 21 l67 7 0 168 c0 106 -4 169 -10 169 -6 0 -10 -60 -10 -159 l0
-159 -62 -7 c-35 -4 -82 -13 -105 -20 -35 -11 -51 -11 -85 0 -24 7 -71 16
-105 20 l-63 7 0 159 c0 99 -4 159 -10 159 -6 0 -10 -63 -10 -169z"/>
</g>
</svg>
                    <!-- <p>Collection</p> -->
                </a>

                {% if current_user.username == admin -%}
                <a class="nav-child" id="admin" href="{{ url_for('admin.index') }}">
                    <svg class="nav-icon icon" id="key-icon" xmlns="http://www.w3.org/2000/svg" enable-background="new 0 0 24 24" viewBox="0 0 24 24"><path d="M21.8534546,2.1587524c-0.1918335-0.1986084-0.5083618-0.2041016-0.7069702-0.0122681l-5.4326172,5.4321899c-0.0072632,0.0065918-0.0167847,0.0089722-0.0237427,0.0161133c-0.0062866,0.0064087-0.0081787,0.0150757-0.0140991,0.0217285l-6.381958,6.3814087C8.5245361,13.3829956,7.5617065,13,6.5,13C4.0147095,13,2,15.0147095,2,17.5S4.0147095,22,6.5,22c2.4841309-0.0026855,4.4973145-2.0158691,4.5-4.5c0-1.0621948-0.3833618-2.0253906-0.9988403-2.795105l6.0498657-6.0493774l1.767334,1.767334c0.0936279,0.0939331,0.2208862,0.1466675,0.3535156,0.1464844v0.000061c0.1325684-0.000061,0.2596436-0.0527344,0.3533936-0.1464233c0.1953125-0.1952515,0.1953125-0.5118408,0.0001221-0.7071533l-1.767334-1.767334l2.1216431-2.121521l1.7677612,1.7677612c0.093689,0.0939331,0.2208862,0.1466675,0.3535156,0.1464844c0.1325684,0,0.2597046-0.0526733,0.3533936-0.1463623c0.1953125-0.1952515,0.1953735-0.5118408,0.0001221-0.7070923L19.586792,5.1199951l2.2666626-2.2665405C22.0406494,2.659729,22.0406494,2.3525391,21.8534546,2.1587524z M6.5,21C4.5670166,21,3,19.4329834,3,17.5S4.5670166,14,6.5,14c1.9320068,0.0023193,3.4976807,1.5679932,3.5,3.5C10,19.4329834,8.4329834,21,6.5,21z"/></svg>
                    <!-- <p>Admin</p> -->
                </a>
                {%- endif %}

                <a class="nav-child" id="logout" href="{{ url_for('app-user.logout') }}">
                    <svg class="nav-icon icon" id="logout-icon" xmlns="http://www.w3.org/2000/svg" data-name="1" viewBox="0 0 128 128"><path d="M98 124H38V4h60a2 2 0 0 0 0-4H18A18 18 0 0 0 0 18v92a18 18 0 0 0 18 18h80a2 2 0 0 0 0-4ZM4 110V18A14 14 0 0 1 18 4h16v120H18a14 14 0 0 1-14-14Z"/><path d="m127.41 62.59-30-30a2 2 0 0 0-2.82 2.82L121.17 62H58a2 2 0 0 0 0 4h63.17L94.59 92.59a2 2 0 1 0 2.82 2.82l30-30a2 2 0 0 0 0-2.82Z"/></svg>
                    <!-- <p>Log Out</p> -->
                </a>
            </section>
        </div>
        <div id="profile">
            <div id="messages-container">
                <svg class="icon" id="message-icon" xmlns="http://www.w3.org/2000/svg" width="32" height="32" fill="#fff" viewBox="0 0 32 32"><path fill="#fff" d="M4 21C4 18.7909 5.79086 17 8 17H24C26.2091 17 28 18.7909 28 21C28 23.2091 26.2091 25 24 25H8C5.79086 25 4 23.2091 4 21ZM8 19C6.89543 19 6 19.8954 6 21C6 22.1046 6.89543 23 8 23H24C25.1046 23 26 22.1046 26 21C26 19.8954 25.1046 19 24 19H8Z" clip-rule="evenodd"/><path fill="#000" d="M13 28C13 27.4477 13.4477 27 14 27H18C18.5523 27 19 27.4477 19 28V28C19 28.5523 18.5523 29 18 29H14C13.4477 29 13 28.5523 13 28V28Z"/><path fill="#fff" fill-rule="evenodd" d="M7 14C7 9.02944 11.0294 5 16 5C20.9706 5 25 9.02944 25 14V18H23V14C23 10.134 19.866 7 16 7C12.134 7 9 10.134 9 14V18H7V14Z" clip-rule="evenodd"/><path fill="#fff" fill-rule="evenodd" d="M16 4C15.4477 4 15 4.44772 15 5V6H13V5C13 3.34315 14.3431 2 16 2C17.6569 2 19 3.34315 19 5V6H17V5C17 4.44772 16.5523 4 16 4Z" clip-rule="evenodd"/></svg>
                <div link="{{ url_for('index.messages') }}" class="messages glassmorphism">
                </div>
            </div>
            <a href="{{ url_for('profile._profile') }}" id="profile-picture-main">
                <img src="{{ image_file }}" class="dashboard-profile-picture" alt="">
            </a>
        </div>
    </section>

    <section id="main-section">
        {% block reviewers -%} {%- endblock reviewers %}
        <!--  -->
        {% block profile -%}{%- endblock profile %}
        <!--  -->
        {% block review -%} {%- endblock review %}
    </section>
</div>
{%- endblock main %}