Engine/profile/forms.py
from Engine.helpers import CheckProfanity
from flask_wtf import FlaskForm
from flask_wtf.file import FileField, FileAllowed
from werkzeug.security import check_password_hash
from flask_login import current_user
from wtforms import StringField, SubmitField, TextAreaField, PasswordField, HiddenField, TelField
from Engine.models import User
from wtforms.validators import DataRequired, Length, ValidationError


class profileForm(FlaskForm):
    submit = SubmitField('UPDATE', id="save-button")

    profilePicture = FileField('Update Profile Picture', validators=[
                               FileAllowed(['jpeg', 'png', 'jpg', 'webp'])])

    first_name = StringField('First Name', id="first-name", validators=[DataRequired(
        message="Please add your username"), Length(max=50), CheckProfanity()])

    last_name = StringField('Last Name', id="last-name", validators=[DataRequired(
        message="Please add your last name"), Length(max=50), CheckProfanity()])

    school = StringField(u'School', id="school", validators=[
        Length(max=300), CheckProfanity()])

    course = StringField('Course', id="course", validators=[Length(
        max=200, message="150 character limit"), CheckProfanity()])

    phone = TelField(
        validators=[Length(max=15, message="Accepts 15 numbers only")])


class ChangePassword(FlaskForm):
    password = PasswordField(
        id="old-password-input", validators=[DataRequired("Please input old password")])

    def validate_password(self, password):
        user = User.query.filter_by(email=current_user.email)

        if check_password_hash(user, password.data) == False:
            raise ValidationError("Password does not match database records")

    newPassword = PasswordField('Enter new Password', id="new-password-input",
                                validators=[DataRequired("PLease input new password")])

    update = SubmitField(u'UPDATE', id="new-password-update-button")


class MessageForm(FlaskForm):
    message = TextAreaField('Message', validators=[
        DataRequired(), CheckProfanity(), Length(min=0, max=140)])
    submit = SubmitField('Submit')

Engine/profile/routes.py
from flask import Blueprint

from flask import flash, redirect, render_template, request, url_for
from Engine import db
from Engine.models import User
from werkzeug.security import check_password_hash, generate_password_hash
from flask_login import current_user, login_required
from Engine.helpers import save_picture
from Engine.profile.forms import (profileForm, ChangePassword)

profile = Blueprint('profile', __name__,
                    template_folder='templates/profile', static_folder='static/profile')


@profile.get("/profile")
@login_required
def _profile():
    pageTitle = "Profile"
    image_file = url_for(
        'static', filename='profile_pictures/' + current_user.profile_picture)
    return render_template("profile.html", pageTitle=pageTitle, image_file=image_file, user=db.session.get(User, current_user.id))


@profile.route("/edit", methods=["POST", "GET"])
@login_required
def edit_profile():

    pageTitle = "Edit Profile"
    form = profileForm()
    passForm = ChangePassword()
    image_file = url_for(
        'static', filename='profile_pictures/' + current_user.profile_picture)

    if request.method == "POST":
        if form.validate_on_submit():
            if form.profilePicture.data:
                current_user.profile_picture = save_picture(
                    form.profilePicture.data)

            current_user.first_name = form.first_name.data
            current_user.last_name = form.last_name.data
            current_user.school = form.school.data
            current_user.course = form.course.data
            current_user.phone = form.phone.data
            flash('Successfully updated profile')
            db.session.commit()
            return redirect(url_for('profile._profile'))
        else:
            return render_template('edit-profile.html', pageTitle=pageTitle, form=form, image_file=image_file, passForm=passForm, error=form.errors)
    else:
        image_file = url_for(
            'static', filename='profile_pictures/' + current_user.profile_picture)

        form.first_name.data = current_user.first_name
        form.last_name.data = current_user.last_name
        form.school.data = current_user.school
        form.course.data = current_user.course
        form.phone.data = current_user.phone

        return render_template("edit-profile.html", pageTitle=pageTitle, form=form, image_file=image_file, passForm=passForm)


@profile.route("/change-password", methods=["POST"])
@login_required
def changePassword():
    form = ChangePassword()

    if form.validate_on_submit():
        if check_password_hash(current_user.password, form.password.data):
            current_user.password = generate_password_hash(
                form.newPassword.data)
            db.session.commit()

            return redirect(url_for('index._index'))
        else:
            form.form_errors.append("Passwords does not match")
            return render_template("profile.html", form.form_errors)
    else:
        return render_template("profile.html", form.form_errors)

Engine/profile/templates/profile/edit-profile.html
{% extends 'navigation.html' %}

<!-- {# styles #} -->
{%- block component_style %}
<link rel="stylesheet" href="{{ url_for( 'profile.static' , filename='edit-profile.css')  }}"> {% endblock component_style -%}

<!-- {# scripts #} -->
{%- block component_script %}
<script src="{{ url_for( 'profile.static' , filename='edit-profile.js')  }}" type="module"></script>
{% endblock component_script -%}

<!-- {# profile section #} -->
{%- block profile -%}

<!-- displays form errors -->
{% if form.errors %}
<ul class="error-list">
    {% for field_name,field_errors in form.errors|dictsort if field_errors %} {% for error in field_errors %}
    <div class="error">{{ field_name }} {{ error }}</div>
    {% endfor %} {% endfor %}
</ul>
{% endif %}

<div id="profile-section">

    {% include 'newPassword.html' %}

    <form action="{{ url_for('profile.edit_profile') }}" method="post" class="profile-main" enctype="multipart/form-data">

        {{ form.csrf_token }}
        <!-- Top Section -->
        <div class="profile-top">

            <!-- Top Section Controls -->
            <div class="profile-top-controls">
                <!-- submit button -->
                {{ form.submit }}
            </div>
            <!-- Profile Picture Container -->
            <div id="profile-username-container">
                <div class="profile-picture-container">
                    <div class="profile-picture-big">
                        <!-- Profile picture src -->
                        <img src="{{ image_file }}" id="actual_picture" alt="">
                        <div class="camera-icon-container">
                            <!-- Profile picture input -->
                            {{ form.profilePicture(class="input-profile-picture")}}
                            <svg class="icons" id="camera-icon" xmlns="http://www.w3.org/2000/svg" enable-background="new 0 0 32 32" viewBox="0 0 32 32"><path d="M28,7.65997h-4.41998c-0.17999,0-0.35004-0.09998-0.44-0.25995l-1.22003-2.22003c-0.62-1.12-1.78998-1.81-3.07001-1.81h-5.69995c-1.28003,0-2.45001,0.69-3.07001,1.81L8.85999,7.40002C8.77002,7.56,8.59998,7.65997,8.41998,7.65997H4c-1.92999,0-3.5,1.57001-3.5,3.5V25.13c0,1.92999,1.57001,3.5,3.5,3.5h24c1.92999,0,3.5-1.57001,3.5-3.5V11.15997C31.5,9.22998,29.92999,7.65997,28,7.65997z M16,24.64001c-3.58002,0-6.5-2.91003-6.5-6.5c0-3.58002,2.91998-6.5,6.5-6.5s6.5,2.91998,6.5,6.5C22.5,21.72998,19.58002,24.64001,16,24.64001z"/><circle cx="16" cy="18.14" r="3.5"/></svg>
                        </div>
                    </div>
                </div>
                <div id="username-container">
                    <!-- Username input -->
                    {{ form.username }}
                </div>
            </div>

        </div>

        <div class="profile-body">
            <!-- Name, Last Name, Address Container  -->
            <div class="name-fields-container">

                <div class="profile-input-field">
                    <div class="input-field-placeholders">
                        {{ form.first_name.label(class="name-label")}}
                        <p class="counter" id="first-name-counter"><span>0</span>/60</p>
                    </div>
                    <!-- first name input -->
                    {{ form.first_name(class="first-name", placeholder="Add your first name")}}
                </div>

                <div class="profile-input-field">
                    <div class="input-field-placeholders">
                        {{ form.last_name.label(class="name-label")}}
                        <p class="counter" id="last-name-counter"><span>0</span>/60</p>
                    </div>
                    <!-- last name input -->
                    {{ form.last_name(class="last-name", placeholder="Add your last name")}}
                </div>

            </div>

            <!-- Address -->
            <div class="profile-input-field">
                <div class="input-field-school">
                    {{ form.school.label(class="school-label")}}
                    <p class="counter" id="school-counter"><span>0</span>/300</p>
                </div>
                <!-- school input -->
                {{ form.school(placeholder="Ramon Magsaysay Memorial Colleges Inc. (optional)")}}
            </div>

            <!-- Skills -->
            <div class="profile-input-field">
                <div class="input-field-details">
                    {{ form.course.label(class="course-label")}}
                    <p class="counter" id="course-counter"><span>0</span>/200</p>
                </div>
                <!-- course input -->
                {{ form.course(placeholder="Add your course")}}
            </div>

            <!-- Contact Number -->
            <div class="profile-input-field">
                {{ form.phone.label(class="phone-label")}}
                <!-- contact number input -->
                {{ form.phone(class="contact-number",placeholder="+63")}}
            </div>
        </div>

        <!-- Bottom Section -->
        <div class="profile-bottom">
            <div class="change-password">CHANGE PASSWORD</div>
            <a class="profile-close-button">CANCEL</a>
        </div>

    </form>
</div>
{%- endblock profile %}

Engine/profile/templates/profile/newPassword.html
{% block newPassword -%}
<div class="new-password-modal">
    <form id="new-password-form" action="{{ url_for('profile.changePassword') }}" method="post">

        {{ passForm.csrf_token }}
        <p class="new-password-title">CHANGE PASSWORD</p>

        <div class="new-password-block">
            <label class="new-password-labels" for="verify-password">Verify Password</label>
            <div class="new-password-input-field">
                <!-- old password input -->
                {{ passForm.password(class="password-input") }}
                <div class="icon-container" id="verify-eyes-icon-container">
                    <svg version="1.0" id="verify-eye" class="new-password-eye icons" viewBox="0 0 700.000000 700.000000" preserveAspectRatio="xMidYMid meet"><metadata>Created by potrace 1.12, written by Peter Selinger 2001-2015</metadata><g transform="translate(0.000000,700.000000) scale(0.100000,-0.100000)" fill="#000000" stroke="none"><path d="M3235 5364 c-687 -67 -1302 -310 -1895 -747 -186 -137 -308 -243 -506 -441 -295 -296 -520 -588 -719 -935 -127 -222 -139 -276 -86 -386 71 -152 240 -204 388 -119 51 29 75 61 138 179 248 465 663 936 1125 1277 166 122 310 210 515 313 330 167 645 264 995 305 711 85 1425 -118 2080 -588 484 -348 927 -845 1188 -1332 50 -93 77 -126 126 -155 142 -83 308 -34 384 114 57 113 46 167 -81 387 -194 337 -416 623 -715 924 -319 322 -595 537 -947 740 -251 145 -632 304 -865 360 -339 83 -477 101 -805 105 -154 1 -298 1 -320 -1z"></path><path d="M3370 4304 c-14 -3 -64 -11 -111 -19 -385 -64 -752 -331 -942 -686 -49 -92 -105 -245 -130 -358 -30 -131 -31 -402 -3 -536 84 -404 340 -744 702 -932 387 -202 855 -198 1242 8 351 187 593 508 684 908 30 131 32 402 4 536 -113 544 -537 962 -1074 1061 -85 16 -323 27 -372 18z m326 -565 c507 -132 755 -710 500 -1163 -144 -255 -403 -406 -696 -406 -408 0 -738 292 -790 699 -50 393 203 766 590 870 107 28 287 29 396 0z"></path></g></svg>
                    <svg version="1.0" id="verify-eye-off" class="new-password-eye-off icons" viewBox="0 0 700.000000 700.000000" preserveAspectRatio="xMidYMid meet"><metadata>Created by potrace 1.12, written by Peter Selinger 2001-2015</metadata><g transform="translate(0.000000,700.000000) scale(0.100000,-0.100000)" fill="#000000" stroke="none"><path d="M420 5084 c-111 -48 -159 -193 -97 -291 82 -129 501 -532 715 -687 28 -21 52 -42 52 -47 0 -5 -67 -96 -148 -202 -81 -106 -220 -286 -307 -401 -88 -114 -192 -250 -232 -301 -39 -51 -79 -108 -89 -127 -21 -41 -22 -134 -1 -174 20 -39 75 -90 110 -103 40 -16 132 -13 170 3 47 21 64 39 157 161 46 61 136 178 199 260 63 83 170 220 236 307 66 86 153 199 193 252 l73 96 52 -29 c275 -152 529 -258 862 -356 28 -8 72 -20 99 -25 27 -6 56 -15 66 -20 20 -11 22 3 -75 -465 -30 -148 -74 -358 -96 -465 -66 -322 -73 -369 -60 -418 35 -127 180 -188 301 -127 84 43 96 69 157 368 29 144 71 352 94 462 22 110 57 281 77 380 l37 180 45 0 c25 -1 145 -7 267 -14 181 -10 264 -10 450 0 125 7 246 13 268 14 l40 0 37 -180 c20 -99 55 -270 77 -380 23 -110 65 -318 94 -462 61 -299 73 -325 157 -368 121 -61 266 0 301 127 13 49 6 96 -60 418 -22 107 -66 317 -96 465 -31 149 -64 312 -74 363 l-18 94 21 8 c11 5 66 21 121 35 361 94 789 281 1075 469 30 20 60 36 66 36 7 0 30 -35 51 -77 534 -1049 526 -1033 559 -1067 38 -39 83 -56 148 -56 66 0 102 12 139 48 51 48 69 88 70 151 0 55 -7 71 -183 417 -101 197 -209 409 -240 469 -145 279 -192 377 -184 385 5 4 42 36 83 70 172 147 443 425 498 513 47 74 29 191 -39 254 -57 53 -159 68 -233 34 -25 -11 -75 -57 -134 -122 -467 -514 -973 -854 -1581 -1061 -734 -250 -1634 -252 -2370 -3 -173 58 -243 87 -410 167 -441 211 -822 500 -1181 897 -59 66 -109 111 -134 122 -48 22 -127 24 -175 3z"></path></g></svg>
                </div>
            </div>
        </div>

        <div class="new-password-block">
            <label class="new-password-labels" for="new-password">Enter New Password</label>
            <div class="new-password-input-field">
                <!-- new password input -->
                {{ passForm.newPassword(class="password-input") }}
                <div class="icon-container" id="new-password-eyes-icon-container">
                    <svg version="1.0" id="new-password-eye" class="new-password-eye icons" viewBox="0 0 700.000000 700.000000" preserveAspectRatio="xMidYMid meet"><metadata>Created by potrace 1.12, written by Peter Selinger 2001-2015</metadata><g transform="translate(0.000000,700.000000) scale(0.100000,-0.100000)" fill="#000000" stroke="none"><path d="M3235 5364 c-687 -67 -1302 -310 -1895 -747 -186 -137 -308 -243 -506 -441 -295 -296 -520 -588 -719 -935 -127 -222 -139 -276 -86 -386 71 -152 240 -204 388 -119 51 29 75 61 138 179 248 465 663 936 1125 1277 166 122 310 210 515 313 330 167 645 264 995 305 711 85 1425 -118 2080 -588 484 -348 927 -845 1188 -1332 50 -93 77 -126 126 -155 142 -83 308 -34 384 114 57 113 46 167 -81 387 -194 337 -416 623 -715 924 -319 322 -595 537 -947 740 -251 145 -632 304 -865 360 -339 83 -477 101 -805 105 -154 1 -298 1 -320 -1z"></path><path d="M3370 4304 c-14 -3 -64 -11 -111 -19 -385 -64 -752 -331 -942 -686 -49 -92 -105 -245 -130 -358 -30 -131 -31 -402 -3 -536 84 -404 340 -744 702 -932 387 -202 855 -198 1242 8 351 187 593 508 684 908 30 131 32 402 4 536 -113 544 -537 962 -1074 1061 -85 16 -323 27 -372 18z m326 -565 c507 -132 755 -710 500 -1163 -144 -255 -403 -406 -696 -406 -408 0 -738 292 -790 699 -50 393 203 766 590 870 107 28 287 29 396 0z"></path></g></svg>
                    <svg version="1.0" id="new-password-eye-off" class="new-password-eye-off icons" viewBox="0 0 700.000000 700.000000" preserveAspectRatio="xMidYMid meet"><metadata>Created by potrace 1.12, written by Peter Selinger 2001-2015</metadata><g transform="translate(0.000000,700.000000) scale(0.100000,-0.100000)" fill="#000000" stroke="none"><path d="M420 5084 c-111 -48 -159 -193 -97 -291 82 -129 501 -532 715 -687 28 -21 52 -42 52 -47 0 -5 -67 -96 -148 -202 -81 -106 -220 -286 -307 -401 -88 -114 -192 -250 -232 -301 -39 -51 -79 -108 -89 -127 -21 -41 -22 -134 -1 -174 20 -39 75 -90 110 -103 40 -16 132 -13 170 3 47 21 64 39 157 161 46 61 136 178 199 260 63 83 170 220 236 307 66 86 153 199 193 252 l73 96 52 -29 c275 -152 529 -258 862 -356 28 -8 72 -20 99 -25 27 -6 56 -15 66 -20 20 -11 22 3 -75 -465 -30 -148 -74 -358 -96 -465 -66 -322 -73 -369 -60 -418 35 -127 180 -188 301 -127 84 43 96 69 157 368 29 144 71 352 94 462 22 110 57 281 77 380 l37 180 45 0 c25 -1 145 -7 267 -14 181 -10 264 -10 450 0 125 7 246 13 268 14 l40 0 37 -180 c20 -99 55 -270 77 -380 23 -110 65 -318 94 -462 61 -299 73 -325 157 -368 121 -61 266 0 301 127 13 49 6 96 -60 418 -22 107 -66 317 -96 465 -31 149 -64 312 -74 363 l-18 94 21 8 c11 5 66 21 121 35 361 94 789 281 1075 469 30 20 60 36 66 36 7 0 30 -35 51 -77 534 -1049 526 -1033 559 -1067 38 -39 83 -56 148 -56 66 0 102 12 139 48 51 48 69 88 70 151 0 55 -7 71 -183 417 -101 197 -209 409 -240 469 -145 279 -192 377 -184 385 5 4 42 36 83 70 172 147 443 425 498 513 47 74 29 191 -39 254 -57 53 -159 68 -233 34 -25 -11 -75 -57 -134 -122 -467 -514 -973 -854 -1581 -1061 -734 -250 -1634 -252 -2370 -3 -173 58 -243 87 -410 167 -441 211 -822 500 -1181 897 -59 66 -109 111 -134 122 -48 22 -127 24 -175 3z"></path></g></svg>
                </div>
            </div>
        </div>

        <div class="new-password-footer">
            <button id="new-password-close-button">CANCEL</button>
            <!-- update button -->
            {{ passForm.update }}
        </div>
    </form>
</div>
{%- endblock newPassword %}

Engine/profile/templates/profile/profile.html
{% extends 'navigation.html' %}

<!-- {# styles #} -->
{%- block component_style %}
<link rel="stylesheet" href="{{ url_for( 'profile.static' , filename='profile.css')  }}"> {% endblock component_style -%}

<!-- {# scripts #} -->
{%- block component_script %}
<script src="{{ url_for( 'profile.static' , filename='profile.js')  }}" type="module"></script>
{% endblock component_script -%}

<!-- {# profile section #} -->
{%- block profile -%}


<div id="profile-section">

    <div id="profile-main">

        <!-- Top Section -->
        <div class="profile-top">

            <!-- Profile Picture Container -->
            <div id="profile-username-container">
                <div class="profile-picture-container">
                    <div class="profile-picture-big">
                        <!-- Profile picture src -->
                        <img src="{{ image_file }}" id="actual_picture" alt="">
                    </div>
                </div>
                <div id="username-container">
                    <!-- Username input -->
                    <p id="username">{{ user.username }}</p>
                </div>
            </div>

        </div>

        <div class="profile-body">
            <!-- Name, Last Name, Address Container  -->
            <div class="name-fields-container">

                <div class="profile-data">
                    <label class="school-label">Name</label>
                    <div id="name">
                        <p class="user-info" id="first-name">
                            {% if user.first_name == None -%}
                            <!--  -->
                            Add first name
                            <!--  -->
                            {%- else -%}
                            <!--  -->
                            {{user.first_name}}
                            <!--  -->
                            {%- endif %}
                        </p>
                        <p class="user-info" id="last-name">
                            {% if user.last_name == None -%}
                            <!--  -->
                            Add last name
                            <!--  -->
                            {%- else -%}
                            <!--  -->
                            {{user.last_name}}
                            <!--  -->
                            {%- endif %}
                        </p>
                    </div>
                </div>

                <!-- Address -->
                <div class="profile-data">
                    <label for="school" class="school-label">School</label>
                    <!-- school input -->
                    <p class="user-info" id="school">
                        {% if user.school == None -%}
                        <!--  -->
                        Add your school
                        <!--  -->
                        {%- else -%}
                        <!--  -->
                        {{user.school}}
                        <!--  -->
                        {%- endif %}
                    </p>
                </div>

                <!-- Skills -->
                <div class="profile-data">
                    <label for="course" class="course-label">Course</label>
                    <!-- course input -->
                    <p class="user-info" id="course">
                        {% if user.course == None -%}
                        <!--  -->
                        Add your course
                        <!--  -->
                        {%- else -%}
                        <!--  -->
                        {{user.course}}
                        <!--  -->
                        {%- endif %}
                    </p>
                </div>

                <!-- Contact Number -->
                <div class="profile-data">
                    <label for="phone" class="number-country-label">Phone Number</label>
                    <!-- contact number input -->
                    <p class="user-info">
                        <p class="user-info" id="phone">
                            {% if user.phone == None -%}
                            <!--  -->
                            Add your phone number
                            <!--  -->
                            {%- else -%}
                            <!--  -->
                            {{user.phone}}
                            <!--  -->
                            {%- endif %}
                        </p>
                    </p>
                </div>
            </div>

            <!-- Bottom Section -->
            <div class="profile-options">
                {% if current_user %}
                <a href="{{ url_for('profile.edit_profile') }}" class="button">Edit</a>
                <!--  -->
                {% endif %}
                <a class="button" id="return-to-previous">Return</a>
                <div id="message" class="button">
                    Message
                </div>
            </div>

            </form>
        </div>
        {%- endblock profile %}